### ISSUE TITLE
[1.16.3] Bag stops giving loot after adding more than 32 entries to the tagList. (stop working on the 33rd entry)

### ISSUE THREAD

**Issue by Gbergz** [CodersDownUnder/Loot-Bag-Mod#11]
Minecraft Version: 1.16.3
Mod Version: lootbagmod-1.16.3-1.6.1

**Describe the bug**
Bag stops giving loot after adding more than 32 entries to the tagList. (stop working on the 33rd entry)
Hard to explain exactly but hope you understand.

**To Reproduce**
1. Add the mod
2. Add 33 entries to the tagList
3. start game
4. Give bag, use it
5. bag drops nothing

**Expected behavior**
That the bag is working and drops the items.

**Screenshots / GIF**
https://gyazo.com/bc2e2199f5d7596e78a344127690f6d7

**Logs**
[latest.log](https://github.com/CodersDownUnder/Loot-Bag-Mod/files/5387566/latest.log) (**looking at the bottom you can see the errors when adding the 33rd tagList entry**)

**Additional context**
Here's the [taglist](https://hastebin.com/unojixuwuv.lua) I'm currently using. When removing the last entry ``"forge:seeds"`` the bag starts working again, and it doesn't have to be that specific entry, any tag entry makes it stop dropping items.

**Comment by Trhod17** [comment]
Fixed and updated.
[https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3082438](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3082438)
