### ISSUE TITLE
Crash on game loading with 1.6.3 

### ISSUE THREAD

**Issue by 3x1at1on** [CodersDownUnder/Loot-Bag-Mod#13]
Minecraft Version: 1.16.3
Forge version: 34.1.42
Mod Version: 1.6.3

**Describe the bug**
Crash on loading minecraft (mod scanning/construction phase)

**To Reproduce**
Start the game

**Expected behavior**
Game to load normally

**Additional context**
https://pastebin.com/zPWtns1Q Log starts with "You're mean" hence the offensive warning!

**Comment by Trhod17** [comment]
Fixed in v1.6.4.
