### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by therealeric** [CodersDownUnder/Loot-Bag-Mod#14]
[crash-2020-11-09_02.59.45-fml.txt](https://github.com/CodersDownUnder/Loot-Bag-Mod/files/5509389/crash-2020-11-09_02.59.45-fml.txt)
Minecraft Version: 1.16.4
Mod Version: 1.6.3

**Describe the bug**
Mod loading error has occurred

**To Reproduce**
Install mod,
Run...

**Expected behavior**
Minecraft game to load and run...

**Additional context**

**Comment by Trhod17** [comment]
Fixed in v1.6.4

**Comment by therealeric** [comment]
Mod version 1.6.4 solved problems in Minecraft 1.16.3 & 1.16.4...

Thank you.
