### ISSUE TITLE
modblacklist field not functioning

### ISSUE THREAD

**Issue by mecha-moonboy** [CodersDownUnder/Loot-Bag-Mod#15]
After adding each mod to blacklist, it still chooses items from them.

**Comment by Trhod17** [comment]
What version are you using? i cant seem to reproduce this issue with the latest version.

Can you upload your config file so i take a look at it

**Comment by mecha-moonboy** [comment]
[lootbagmod-client.txt](https://github.com/CodersDownUnder/Loot-Bag-Mod/files/5646706/lootbagmod-client.txt)

**Comment by Trhod17** [comment]
can you upload your debug log aswell

**Comment by Trhod17** [comment]
did you change the file extension from .toml to .txt when you uploaded it
