### ISSUE TITLE
Server Crash w/ Evolved RPG

### ISSUE THREAD

**Issue by WenXin20** [CodersDownUnder/Loot-Bag-Mod#17]
`Minecraft v1.16.5`
`Forge v36.0.1`
`Loot Bags v1.6.4`
[`Evolved RPG v0.2.1`](https://www.curseforge.com/minecraft/mc-mods/evolved-rpg)

**Describe the bug**
- After killing the Deep Crawler from Evolved RPG, my server crashed. 
- And I'm unsure of which mod is the true cause of the crash.
- I also made a comment on their mod page.

**To Reproduce**
1. Spawn Deep Crawler
2. Kill it
3. Crash the server

**Expected behavior**
- No crashes

**Additional context**
- [Crash Report
](https://gist.github.com/WenXin20/d038bf5a83a21da60f77c57f16141583)

**Comment by Trhod17** [comment]
It appears to be an issue on there side. i believe its caused by registering the entity renderer on the serverside, but im not sure

**Comment by WenXin20** [comment]
Alright, thanks. I also randomly got the same crash again, but it mentions both the Quark Toretoise and the Evolved RPG Deep Crawler.
[Crash Report](https://gist.github.com/WenXin20/aa6da5fb51db1c363c9ebceccf6e4294)

**Comment by Trhod17** [comment]
Turns out the issue was on my side it has been fixed and a new version of loot bag mod has been released https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3181715

**Comment by WenXin20** [comment]
Thanks!
