### ISSUE TITLE
[1.16.5]Can you add the Mod whitelist configuration?

### ISSUE THREAD

**Issue by EnterFor** [CodersDownUnder/Loot-Bag-Mod#18]
As the title says, I only want to drop items from a certain Mod....
Can you add it? please...

**Comment by Trhod17** [comment]
the mod whitelist is in all versions 1.16.2 and up

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/106121942-0db25100-6150-11eb-87b7-6af116d09aa9.png)
I only found the mod blacklist..

**Comment by EnterFor** [comment]
Sorry, I mean [modwhitelist]
I am very sorry, I am a Chinese player, English is not good

**Comment by Trhod17** [comment]
https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3184320 added by changing the mod blacklist to be both a blacklist and a whitelist
