### ISSUE TITLE
Loot bags no longer drop after update

### ISSUE THREAD

**Issue by Staegrin** [CodersDownUnder/Loot-Bag-Mod#19]
Minecraft Version: 1.16.5
Mod Version: lootbagmod-1.16.5-1.6.5.jar & lootbagmod-1.16.5-1.6.6.jar

**Describe the bug**
After the recent updates Loot bags no longer drop when killing endermen or creepers. 

**To Reproduce**
After updating not a single loot bag dropped after killing over a 100 creepers and endermen. Even using a sword with looting 50 resulted in no loot bags dropping. 

The configs were not changed. Only the mod was updated.

Rolling back to version lootbagmod-1.16.3-1.6.4.jar results in bags dropping again.

**Expected behavior**
bags dropping when mobs are killed

**Comment by Trhod17** [comment]
The mob drop config was changed to use registry names 

so for creeper you need to use minecraft:creeper instead of just creeper
and for enderman you need to use minecraft:enderman

**Comment by Staegrin** [comment]
I'll try again to delete the config and then update.

**Comment by Staegrin** [comment]
That did indeed fix it. Though can I strongly recommend mentioning this on the main page of the curseforge page.
