### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by vertex101** [CodersDownUnder/Loot-Bag-Mod#22]
Minecraft Version: 1.16.5
Mod Version: 2.3.0

**Describe the bug**
Spamming console with https://i.imgur.com/BqRamXm.png

**To Reproduce**

**Expected behavior**
remove the debug messages from the code 

**Screenshots**
in the LootHandler class
https://i.imgur.com/FAU0ET7.png

**Additional context**

also all the debug/modpack options are set to false but still getting them messages
https://i.imgur.com/Xnzr5LC.png

**Comment by vertex101** [comment]
i was going to send a pull request with a fix to the code but the 1.16.5 code is not here to do that

**Comment by Trhod17** [comment]
Fixed and updated https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3384532
