### ISSUE TITLE
[1.16.5] Whitelist not work

### ISSUE THREAD

**Issue by Daejangnamu** [CodersDownUnder/Loot-Bag-Mod#23]
forge-1.16.5-36.1.32
lootbagmod-1.16.5-2.3.1

Whitelist does not work when using the /reload command.
Restart the minecraft client and it should work fine.

config: https://paste.dimdev.org/fewosuyapu.bash

**Comment by Trhod17** [comment]
The lootbagmod config is a client side config and as such is reloaded using the reload command. The only configs that are reloaded when using the /reload command are the world specific server configs which lootbagmod dosent have.
