### ISSUE TITLE
Whitelist bug

### ISSUE THREAD

**Issue by LokyLive** [CodersDownUnder/Loot-Bag-Mod#3]
Minecraft Version: 1.14.4
Mod Version: 1.1

**Describe the bug**
Whitelist system won't work correctly.

1- I've just change stone for coarse and it still drop stone
https://paste.dimdev.org/axasayibaw.m

2- I've tryed multiple item whitelist and nothing drop
https://paste.dimdev.org/elijofugad.m

PS: Could whitelist support quantity/chance for each items ?

**Comment by Trhod17** [comment]
you have a space in one of the item strings which is causing it your issue
whitelist = ["minecraft:stone", "minecraft:coarse_dirt ", "minecraft:dirt", "minecraft:andesite" ]           
..................................................................................^
