### ISSUE TITLE
Stacks of nonstackables

### ISSUE THREAD

**Issue by Seegras** [CodersDownUnder/Loot-Bag-Mod#5]
Right now, it also gives stacks of nonstackable items. 

Which is quite a annoying. Yes, I want people to get a cool sword, but not 5 of them. On the other hand if they get terracotta, they might as well get 1-64 of them.

So could you make it possible it only gives one of nonstackables, no matter how big the other loot stacks are?

**Comment by Trhod17** [comment]
added
