### ISSUE TITLE
[bug][1.15.2] bag drop issue.

### ISSUE THREAD

**Issue by Bass2style** [CodersDownUnder/Loot-Bag-Mod#6]
Minecraft Version: 1.12.2
Mod Version: 1.5.1

**Describe the bug**
lootbags still drops on some mobs, when it's disabled in config.
actually spotted mobs :
- endermans
- creepers
- phantoms

EDIT : Drowned and Cave Spiders seems also affected.
edit2 : and blazes
edit 3 : and Shulkers
edit 4 : pillagers also drop bags.

there is also a second bug with that behavior, bag drop is affected by looting, i have Apotheosis in my pack, without looting, i get a bag somethime, but with looting IV, i got 5 bags per mob kill. Looting enchant should not affect the number of bags that are dropping, only the drop chance.

**To Reproduce**
1. find a mob listed above
2. kill it (with looting for more cheatyness)
3. enjoy

**Expected behavior**
when disabled in config, no drops, it's working of most of other mobs. (need to see if they are other mobs affected, btw), and should NOT drop multiple bags per mob.

**Screenshots**
No screenshot availlable, but i can record a video if you want. i can also try only with the Bag mod if you want.
edit : video added : https://www.youtube.com/watch?v=sWGIY00bzfI

**Additional context**
nothing revelant to say.

**Comment by Trhod17** [comment]
Hopefully fixed in 1.15.2-V1.5.2 https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/2918950 i am going to close this but feel free to reopen this issue if you find any more bugs

**Comment by Bass2style** [comment]
Phantoms, shulkers and pillagers are still dropping bags when it's disabled in config, but the number of bags seems no more affected by Looting. (creepers, endermens and blaze seems fixed.)

**Comment by Bass2style** [comment]
found a new mob that drop bags, Ghasts are also dropping, when it's disabled in config file.
edit : Ravagers also drop bags.
edit 2 : Magma Cubes seems also to drop.

**Comment by Bass2style** [comment]
any news about this ? ^^ i like the mod, but actually, it's "too OP" for the intention i want (too easy to get bags with cheaty stuff), and i don't want to disable the mod, because it's cool. (and one of the only lootbags mods at the moment on 1.15 MC.)

**Comment by Trhod17** [comment]
I should have a fix released soon, i would have done it sooner but im been very busy recently with irl stuff

**Comment by Bass2style** [comment]
okay, no problem, IRL stuff is always more important, so it's understandable. thanks for giving news about a fix. ^^

**Comment by Trhod17** [comment]
heres the fix just in case you havent seen it yet [https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/2944153](url)

**Comment by Bass2style** [comment]
seems now works as intended. thanks for your mod and the support.
