### ISSUE TITLE
[Enhancement] Is it possible to blacklist an item with a Tag? (Oredict)

### ISSUE THREAD

**Issue by Gbergz** [CodersDownUnder/Loot-Bag-Mod#7]
Hey,
Is it possible to blacklist a Tag? (oredict) like cobblestone, fences .
Example. ("<tag:forge:fences> / <tag:minecraft:fences>" tried this but it didn't seem to work unfortunately.

Would help me alot since i'm creating a pack and i'm trying to filter out junk such as cobblestone from appearing in rewards. (tried this: <tag:forge:cobblestone>)

- Gbergz

**Comment by Trhod17** [comment]
Not at the moment but maybe in the future
